spring:
  profiles:
    active: dev
mybatis-plus:
  configuration:
    #  开启驼峰映射
    map-underscore-to-camel-case: true
  #  用了@MapperScan可以不配置接口包，但要配置编译出来的.xml文件位置
  mapper-locations: classpath*:com/march/main/mapper/*.xml