sys:
  #  是否限制多处登陆
  limit-multiple-login: false
spring:
  profiles: common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      max-active: 20
      keep-alive: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-while-idle: true
      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
      #validationQuery参数必须设置为非空字符串
      test-on-return: false
      validation-query: select 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
  cache:
    type: redis
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
  messages:
    encoding: utf-8
mybatis-plus:
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath*:com/xiyou/common/mapper/**/*.xml,
    classpath*:com/xiyou/main/mapper/**/*.xml,
    classpath*:com/xiyou/quartz/mapper/**/*.xml
  type-aliases-package:
    com.xiyou.common.log.entity,
    com.xiyou.main.domain,
    com.xiyou.quartz.domain,
server:
  tomcat:
    uri-encoding: utf-8


